version: "3"

services:
  nginx:
    image: "nginx:alpine"
    ports:
      - 8000:80
    volumes:
      - "../:/usr/share/nginx/html"
      - "./nginx:/etc/nginx/conf.d"
    depends_on:
      - php

    networks:
      - network

  php:
    build: .
    volumes:
      - "../:/var/www/html"
      - "./php/php.ini:/usr/local/etc/php/php.ini"

    networks:
      - network

networks:
  network:
    driver: bridge

